version: '3.8'

services:
  webapp:
    restart: always
    build: 
      context: ./
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    command: bash -c 'python ./goodgame/manage.py collectstatic --noinput && python ./goodgame/manage.py runserver 0.0.0.0:8000'
    
  worker:
    restart: always
    build: 
      context: ./
    volumes:
      - .:/code
    command: bash -c 'python ./goodgame/main.py'