# Generated by Django 3.2.4 on 2022-04-16 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Games', to='API.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Игра',
                'verbose_name_plural': 'Игры',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegramID', models.BigIntegerField(verbose_name='Телеграмм ID')),
                ('telegramUsername', models.CharField(max_length=80, verbose_name='Никнейм в Телеграмм')),
                ('nicknameSteam', models.CharField(max_length=80, verbose_name='Никнейм в стиме')),
                ('aboutMe', models.TextField(verbose_name='О себе')),
                ('isActive', models.BooleanField(default=True, verbose_name='Активен')),
                ('mainGame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserProfiles', to='API.game', verbose_name='Основная игра')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
    ]
